# Generated by Django 5.2 on 2025-04-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_transaction_product_alter_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='barcode',
        ),
    ]
